### PR TITLE
Refined about page

### PR DESCRIPTION
**Pull request by eliemugenzi**
### What's done

- [x] Refined the about page

### CODE REVIEW

**Comment by billyjason** [comment]
Create job, Elie. Can the team photos still have the pop-out when you click on the photos, just in case we want to display more information on each member?

**Comment by eliemugenzi** [comment]
> Create job, Elie. Can the team photos still have the pop-out when you click on the photos, just in case we want to display more information on each member?

It's how it initially was, but I saw @eaprestige  changed it to how you see it now.

**Comment by billyjason** [comment]
Yes, he had said that he would change it and give it another layout.. but he hasn't yet. but I think it will be there of some other sort.

**Comment by eliemugenzi** [comment]
> Yes, he had said that he would change it and give it another layout.. but he hasn't yet. but I think it will be there of some other sort.

@billyjason  should I wait for it then? Or it will be added once he is done?

**Pull request merged**
