### PR TITLE
Ft fixuiconsistancy

### PR DESCRIPTION
**Pull request by eaprestige**

### CODE REVIEW

**Comment by eaprestige** [comment]
Some changes did not take place after deployement such as fonts and colors.
For example..
Local:
Screenshot 2020-06-25 at 21 54 54
After deployment:
Screenshot 2020-06-25 at 21 55 00

**Comment by eliemugenzi** [comment]
@eaprestige you delete the application cache and reload the page, and your changes will reflect.

**Comment by eliemugenzi** [comment]
@eaprestige  can you also check what happened to the subscribe button? It is now transparent.
Screen Shot 2020-06-26 at 12 49 13 AM

**Comment by eaprestige** [comment]
You mean the browser cache? Okay i will check that.

**Pull request merged**
